version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2

    steps:
      - checkout
      - run:
          name: install deps
          command: bundle
      - run:
          name: build
          command: jekyll build
      - run:
          name: depoly
          command: ls -la _site
      
