version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby@3.0.2

    steps:
      - checkout
      - run: gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: build
          command: bundle install
      - run:
          name: build
          command: jekyll build
      - run:
          name: list
          command: ls -al _site
